### ISSUE TITLE
Trebuie sa identific actorii și componentele principale.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#10]

**Comment by cristina555** [comment]
Actorii principali ai aplicaţiei sunt: clienţii, casierii şi adminitratorii.
Componentele principale sunt:
-Componentele principale sunt:
 
*browserul-disponibil pentru client, având alte doua componente: un motor de cautare şi opţiunea de rezervare ;
*serverul de servicii web;
*serverul web;
*serverul bazei de date;
*aplicația de administrator care comunică cu serverul de servicii web, având componenenta de autentificare şi de gestionare a autentificărilor angajaţilor, şi a datelor ce vor ajunge la clienţi.
*aplicația de casier care comunică cu serverul de servicii web, având componenenta de autentificare şi de gestionare a rezervărilor.
