### ISSUE TITLE
Creeaza scriptul pentru popularea bazei de date cu tabele.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#11]
Scriptul trebuie sa contina si setarea constrangerilor tabelelor. Scriptul trebuie sa respecte diagrama ER.

**Comment by MarianaDumitriu** [comment]
[creare_tabele.zip](https://github.com/Bakmy/TiP/files/1935632/creare_tabele.zip)

**Comment by MarianaDumitriu** [comment]
[creare_tabele.zip](https://github.com/Bakmy/TiP/files/1935708/creare_tabele.zip)

**Comment by MarianaDumitriu** [comment]
[creare_tabele.zip](https://github.com/Bakmy/TiP/files/1952713/creare_tabele.zip)

**Comment by MarianaDumitriu** [comment]
[creare_tabele.zip](https://github.com/Bakmy/TiP/files/1978825/creare_tabele.zip)
