### ISSUE TITLE
Creeaza scriptul care populeaza cu date, tabelele din baza de date.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#12]

**Comment by cristina555** [comment]
[populare_tabele.zip](https://github.com/Bakmy/TiP/files/1936137/populare_tabele.zip)

**Comment by cristina555** [comment]
lasati mesaj pe grup de ce mai e nevoie, sau daca mai trebuie sa completez

**Comment by cristina555** [comment]
[populare_tabele_var2.zip](https://github.com/Bakmy/TiP/files/1951984/populare_tabele_var2.zip)
