### ISSUE TITLE
Trebuie sa creez diagrame UML de information flow.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#2]

**Comment by MarianaDumitriu** [comment]
![29019685_1603991559676554_1712864934_n](https://user-images.githubusercontent.com/37477360/37775181-ee667e8e-2dea-11e8-82d4-e751198d5f8c.jpg)

**Comment by MarianaDumitriu** [comment]
Diagrama fluxurilor de informații prezintă schimbul de informații între entitățile sistemului la un nivel ridicat de abstractizare.Fluxurile de informații nu specifică natura informațiilor, mecanismele prin care sunt transmise, secvențele de schimb sau orice condiții de control.
Informațiile sunt comunicate de la o sursă către un receptor sau o țintă. Pentru a obține informații utilizatorii fac o cerere către aplicația web/desktop. Aceasta este trimisă mai departe spre baza de date. În urma interogării acesteia utilizatorul primeste un răspuns.

**Comment by MarianaDumitriu** [comment]
![uml](https://user-images.githubusercontent.com/37477360/39298183-327e1f40-494e-11e8-8049-809b7a0529d9.png)

**Comment by MarianaDumitriu** [comment]
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Vxdc6M2FP01ftwMID7EY%2BKk7UM7szOZzrZPOwooNg1GrpDXzv76CvNlLkrMEsneGu8%2BBC5CyOccXV1dJGZovtr9ysl6%2BQeLaTpzrHg3Q%2Fczx7GtIJR%2FCstrafEcXBoWPImrQq3hMflO6zsr6yaJad4pKBhLRbLuGiOWZTQSHRvhnG27xZ5Z2n3qmixoz%2FAYkbRv%2FZLEYllasWe19t9osljWT7at6soTiV4WnG2y6nkzBz3v%2F5WXV6SuqyqfL0nMtgcm9DBDc86YKI9WuzlNC2xr2Mr7fnnjatNuTjMx6Aa3vOMbSTe0bvK%2BYeK1BqNpozVDdzHJlzSuTpZilcpDWx7mgrMXOmcp49KSsYwWxiVZF5WsdotCJzfk%2B4bTm01OZZm75yRN6%2FISJsuyMb6X9qpBlAu6e%2FNX2Q1WUoOUrajgr7JIdYNfqa1SX4AqtLctl25QmpYHNNb0kko9i6biFkF5UIH4BqDeBADFrnc6QP0JABr6J1QoPiWgqzwi9EaiQvmaJzm92dIns9A6gdXt%2FV4f29qkHdvw3Nh%2BldL9Zlq9rm8fhRhhMxDXI%2Be5IGb8JRdEJCz7GqXJHrBTqjm0%2Bq7XlJprZM8EdUwEeSI5PYmkMcAZeyfEGZ0VZ7Jep0lUSvoUUAcWvvGOxxPIENiqeMJP992YyR9wiLr%2F74bVFz7l%2B1nKrSxg%2B%2Btde1EeLYq%2FfxZBQ1WTbERZWXmpx6YETwyg7pCEykTSZJHJ02hPoDQUVEj20tvqwiqJ4%2BIxd9tlIujjmkTFM7eSemnbz0wa5egYCUCkHfYHAuz0iXR0EBkYIvI2XiXZ5Jj0jo8zxphURaQ6mJyTPJlgpwRU2pZzwl6pioB1cPlFzhsca55kdEUmx6jjOt0B0%2B4zalu%2BGUqRKuLW4miruIPKEvc0fxFsPT1mEfC7gYJZpAg8tTBrG2L2sQwjHWvfaydGqWuDbJmys9qGKFXN2bRSWhwkUZJMlF3fC8DsJVQMr3Y9o9HOr2quqJXf%2B7vJcYo9t8uooseaCpjqPNkBrjRe0MfqlHGxZAuWkfShtQIEDgigu0T8VZilRsuzvw%2BufKY8kQ0sEN%2FfKOHhrwfFi9OmfHECb%2FiHCvFava4jG8GkqW3g70yO3%2BXN5U8qfsf7jMifzTY8qktVfUYQvqDi0NZnjtNURg7fuvV%2FhAdXNRYCYqKN7CNxA1B8W7xqLGSckjxPIkBFC27hDQ7g7RggxMOh68CE1TANzF4NRrN6wmeW7H1N3eGcbhAT%2BKhbRclydVfLSb8iC05dfNDFyh%2Fdq0kyQV4Piq2LAvk7LcagxW7nPak8KGtspdOAOkxNqmH4I2oaKotzSQAhKAFQxVAJuN6RijQpwIWa9TQrYEBS96IU4FkgF4hB1x2qAD%2FsMoNh2leTAjzoA7D1fruAxLGlWTED1mJclGLgsIFDuw6tf1Qzjt%2BtKoShmaFxA%2Fv1uwxtKlCltS9ZBQhmniF1g%2F0G5CY0owEX%2BqdQsx8YsEDjohQA%2FUA4duTovcRwDXkBoIBQd%2BwwYBnJRSmgDr%2FbIX%2F0SIB96KHNaACDqQp2dI8ENbaTUYEP17rYI%2F1Ab0gxFUHCBmv2A57unMTPrgAMiMNjR4IAegFYkS4vYAMFaJ4TeM7EFNAL4qD7HqoADzDT%2BGvtPgB1n4M0K2BqeYTeVA4678HJRBBW2pYhCTggFAg1TwjqtxP6U9PNSZmWdrzRCehyNdbZNAMHfDRWMwhqBsYghhIJoeYEtDdgH8pFu43R6UcogV5Fpl5B6PYaAzbOXJQCXFeTAnrvMgwpAIXdhQTaFXB0hWzUrPBulwOg52eEimUGrWnAmgJXtaYgolz%2Bn9xyAhu6IsX%2Bw1DRD3QsJ6gffeX8tJwj1zsf50eX8V0573HOWbmLq2iCp0cDXgA0oFjLaUwDqkTBVQPG%2B33QWw6IFcsBjbF%2BdDXglfVT9Hwb5i0V%2B7mNaUCVHbhqYLAGPtm61n0jvyuCwO%2BJAKuWBXsaRHB0V6NSBJYVRUXy6uMi4CRfb7L8%2F6UCHT0fTjoVOyBtyzHU9cdN8K6sfzza7yb9mwzBMdZhXnIU60e3S15Zf9fjO7r2WcIFgYo5n7m%2Bf3Sj5VUFJxr3vbAjg2bVUUcGis8Z6HAGwbh8z1UGrQx0zQHAtxDCoWOCDm8QXFNAP4kKbLA5UPFpE1MzwWBcDujqC7SnA%2BpduO%2FsJzTnCsblhCauAg2sK1KBuPnSkQHm5Wn7odDy9WD7NVb08B8%3D
