### ISSUE TITLE
Creeaza documentatia pentru etapa 3.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#28]

**Comment by cristina555** [comment]
Surdu Cristina s-a ocupat de:
    • documentație (identificarea actorilor și a componentelor principale, diagrame de componente si diagrama de stare);
    • script populare baza de date cu valori de test;
    • crearea unor serviciu de join intre 2 tabele care sa contina metoda GET;
    • implementarea unui template pentru pagina de film(pagina jsp si servlet)
    • implementare secțiune de comentarii(+ servlet);
    • implementare pagina de vizualizare a programului(+ servlet)
    • implementare pagina de formular pentru datele utilizatorului în vederea rezervării(+servlet)
    • implementare pagina pentru finalizarea comenzii(+servlet)
    • creare pagina wiki pentru aplicația Web

„Vlad, în calitate de lider, a distribuit task-urile corespunzător, a oferit suportul necesar pentru ce am avut de implementat. Consider ca a făcut o treaba buna în aceasta postura, a venit cu explicatiile necesare când a fost cazul, și cu ajutor în privința lucrului cu GitHub.”


probleme: O problemă a fost afișarea în pagina jsp a programului cu ajutorul servletului. Am încercat sa fac acest lucru fără a folosi AJAX. În final, am rămas la varianta cu AJAX.
