### ISSUE TITLE
Trebuie sa creez diagrame UML de componente.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#3]

**Comment by cristina555** [comment]
![umldiagramadecomponente](https://user-images.githubusercontent.com/37477315/37791663-7a8d240e-2e12-11e8-98f6-ac6c40fe92c3.png)

**Comment by cristina555** [comment]
Diagrama UML de componente. Această diagrama reprezintă componentele principale ale aplicaţiei, şi relaţiile dintre acestea.
Astfel proiectul este compus dintr-o aplicaţie browser, un utilizator obişnuit poate rezerva un film la cinema. 
Aplicaţia Casieri Cinema  vizează gestiune rezervărilor, iar aplicaţia Admini se ocupa cu actualizarea tututor datelor( săli, locuri, filme , program) . Toate aceste sunt strâns legate de serverul de baze de date.
