### ISSUE TITLE
Trebuie sa creez diagrame UML de secventa.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#5]

**Comment by MarianaDumitriu** [comment]
UML secventa administrator

https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7ZtNc6M4EIZ%2FDdcpQGDDMXGSncNM1VTlsLtHGWSsjUAukGM7v34lI74kMsYePhwnuQQaaMz7qKVWCwywiPd%2FpXCz%2FklDRAzbDPcGeDBs2zIdm%2F8TlkNucV0nN0QpDuVJleEZv6HiSmnd4hBljRMZpYThTdMY0CRBAWvYYJrSXfO0FSXNu25ghDTDcwCJbv0bh2ydWz3XrOzfEY7WxZ0tUx5ZwuAlSuk2kfczbLA6%2FuWHY1j4kudnaxjSXc0EHg2wSCll%2BVa8XyAitC1ky697eudo%2BbtTlLAuF0gsr5Bs5aPfhTFOcMZSyGhq2DPC%2FdwvxVYkttosxwdhh0I8%2FkwbsbmNyV0gnID7V5QyzOX9AZeI%2FKIZZpgm%2FJQlZYzG%2FAQiDtyX4i0oEdc9VPJVPu4IjsS1jG64dc1iwncsvkm3jOAELco2YXLjChNSeEtogsofLNyh%2FbuyWSUM3sgRjRFLD%2FyUfQk8v0S277nc3VWNBUjTutZOZtIGZfOMSscVIr4hKbUT8zViGoCjhCiUCuzWmKHnDQzE0R2P16Zqwwhke02BygCpKWTZLRI5PUhUwLlyjVxrSo0sPfI3hMeXsfAM%2Fx4jfuwBZS8iylTt%2BCOzpkC8u6AvSJGoRTUoYzfgEqG0JahjHIbiNq1Emsz6aKW%2BQsBqIWC2ELD7IGBrBO7hGxSjphA%2FhAzdrvKuPaXy4HT%2FgJLwTiQSlYIhzNZHCawmgfxSFGoZxUktas%2FqtjxqYUsRgQy%2FNt23Pb%2B8wy%2BK%2BY2rsUqR2lElzOg2DZC8qp4rnHBkzRVHDKYRYpqjI47ysbsR0vOSEQhx90cpisebkhoAfkNs17yQmurIUpOQHqm5V0DNn5KaOzf7oaY6GpLa7DS1i7MlnsAHIVp6S22o4kfADPgg7GdAAcBtCua3DSg6%2BD5S8rynuDUFQVs6OpSC3jQ9Rx5FV9HfOz2N0mP290PORUdr9%2B5sup6jgDzliAm8llj4GkXPjAVbn0%2F%2FjmRAYJbhoMmPU0oP%2F8hQOe78K3a%2B2e7lndpsSpCW0qnZpnsZSNWRq%2FaOPYK0rxPkpBEJZj2BdFzFERgO5Hmz%2FHaQe8xKjnw7xzg%2FD2NjejJpPCrlLledwF8ajjZwB6N4XiVgJIqTBmNfFLWgHpDieZWB0TrVSVN%2BNYqA9QFGxw7FgvHDcVKMQ3WqwBkuHPWCBaERF1ljeTMLDpaSeFieVLc%2By5u3tJI%2BFhxsvbyBhSpSc3MJ34yFY3g8Y%2FkMiz9AXRz2nBFZ6EWLgCYrnMY5iyIQnjieTxURZSF4DApF2l%2BjsM24KLYZ5ZGQYd7JPSWovnurJNR4GJeEXrjACUeRB8HxbQCfixSh435MQ7ziSt10YKh5sT8mDr38UGqORW60QgHb3vTwoOoP7BGHauBowop09Fnu0pStaUQTSB4rqyJBW6r7za0nu43ZTH6onM%2Fwnf8QYwf5UiTcMspN1X1%2FUPHe25%2FUe1smQuAdIp1T487yukPIa9XFrfQsD1WTRXdweYtFkS7Fu%2F7lnd2evH8g2zurAl5zwUerQXZeXjjlqL8ZG5h%2FgT0N1ld4qC9KdgZ7ylGPYDusfH%2B8NdQx3x0A%2BoROj5WB3x3IKV7LeunF7w6ojsof2H%2B7d%2FQJ4O%2BojVURnhakWpH%2FCBVhp4%2BF774rwtNiHGqBZsCKsKMvlkIxzyT47atEaYxcA3D0Nc%2FPVgNQ9R%2B1BuB0WK28gu%2BHlM%2BHbD3lmrd2ctb5EvHd6pvEvHupPvwEj%2F8D

**Comment by MarianaDumitriu** [comment]
![uml_secventa_admin](https://user-images.githubusercontent.com/37477360/37793720-20b0c2dc-2e18-11e8-8fb4-5d48099f1ae5.jpg)

**Comment by MarianaDumitriu** [comment]
![uml_secventa_client](https://user-images.githubusercontent.com/37477360/37793734-29923ab6-2e18-11e8-832b-d199b1ed93b5.jpg)

**Comment by MarianaDumitriu** [comment]
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7ZzLcqM4FIafhm0XIOTLMnGS6UV3VVdlMTNLGRSsiYxcICdOnn6EETeJtHFaIF%2FSm4BAAv5PRzrnSG0HLNa7v1K0Wf1kEaaO70Y7B9w5vu%2B5gS%2F%2B5CVvRQl0YVEQpySSN9UFj%2BQdlzVl6ZZEOGvdyBmjnGzahSFLEhzyVhlKU%2Fbavu2J0fZTNyjGWsFjiKhe%2BjeJ%2BKoonUG3Lv%2BOSbwqn%2By58soShc9xyraJfJ7jg6f9v%2BLyGpVtyfuzFYrYa6MI3DtgkTLGi6P1boFprm0pW1Hv4YOr1XunOOF9KgRFhRdEt%2FLTQ5QRnDr%2BhIoGbpf5UZwfyfflb6VG4tU3%2BeF2TW9CzlJxzwtOOREq%2FkBLTH%2BxjHDCEnHLknHO1uIGml%2B4rTRaMJrXu6tVqtu4oSTO63K2EaUrvqbixBOHbMspSfCiQu%2BKwidCadlawhJcvXDeHN59qI5XaS76MmZrzNM3ccuu4lpUkd14Kk9f6z4BZNGq0R0msgzJXhhXDdckxIGE0Q1mroHRAOwlxJFU4HVFOH7coDC%2F%2BirMsq3aMAL5s7ZAlR00FPL8DokCAxKVcE5cI%2BjZ1MjTNLrZUGFfzmLmzG8JFtfucPacW5mqnfhk3hYo4yl7xopEHaohabuhkAinHUa9JlGUP6aTSJuZiV46Vwh4HQTcDgK%2BCQK%2BRuAWvaN8cszFjxDHl6s89G0qDw6PDziJbnJ%2FoVYwQtlqL4HXJlBUxZHmOBzUovGtsONTy7IUU8TJS7v5ru%2BXT%2FjFiHhwPVcpUkNXkTBj2zTEslbTJTjQkDdVGuIojTHXGtrjqD67HyHd%2FRiBkGh%2BL0X5eTapATA3Q01tyFOdEIPU4AlQm9ukBqeGbE1taEhqk8PUPu0tCQc%2BjPByttSmKnEFTMAcRGYmFABgW7B514SigzfhkhcjxaUpCLrc0aEUnNkfOQL5DoVlncQcEBgaTcacA4aMT0ezBTixN5qUXpZNWwBdtvA1sx5pC74eY%2F%2BOZEhRlpGwzU9QSt%2F%2BkaayP%2Fk3P%2Fnmw6PgtkBObIL0lEHNLzPAR4cj6uiohoYGQfqnCdKqRYKJIZABVBoCw4E8LvLvBrkjvOIojguM0%2BMwtkIWq%2FaopMCgGtR%2F1hx9AAejeFx2YCSKVo3RFEXNqAekeFy2YLRB1arLr1oR8M5gduyRQBjfHK1iHGpQBcFw5qgnMSiLhcgay4tZhPAUx8ObSXWbUd60o5eYWITw9ZQHyVWRmrtL9O4sAmcmPJZrWBAC6oLxLBiRhZ60CFnyRNJ1waI0hAeB56osokoOj0GhdPsbFLZZvuPEjQtLyIgY5B4S3Dy9VBKqPYxLQk9chGjLq%2FEoxe84fSlsI6QEJxcMwlM94vmYIPTEQ8jW9cDUAHEt%2BgN%2FxEkaBJqwuSP6KE9ZylcsZgmi93WpIkGXk%2FsNNt3cVhxTXKoiGXHyH%2Bb8Te6EFEbIRFH93B8s3wX3J5nejhAIfECkt1PcW144hLxeU9xaz%2BpSHSbCweUtl0P6pO3Myzu5PHn%2FQLYP1gNm7aUeLfvYe2HhUEPmYjUw%2FQJ7GOxc4aFum%2BwN9lBDBsH2WAc%2Fv9XTMXcSAD2U021l4NXTMohqzamzbsnOfPW0ekHzthDo4eDvSI6VH7YLUs3Pn0N%2BODCxDG46P2wX41DLNQPmhwN96fQrX2kpLRDoC6DNlEwjPyaJtJNmsvBa0IyaMQguwoNT94IGnf89Q1fQhAcXWPLgmpN8YHeSN7bvU10%2BHG6vG%2BzhrZ1%2Bv1cjlzH7PTzOTRqk3xcULy5KGbLf%2B0dRGytKsTuAqcFF4H82SlH82wGjFGhia6B5kHYtUo0vzgLkKe4OtItR%2FbkCY%2FFmAAeLN6GJ7YGmMVoeVk1h1MbnATHqmwM3QoQqVbAkFF%2Fy7gFlQ03gjhiLQn1LX3P3wNVoDsbUXI%2F%2FUci3QqL368yTTW0aQNe%2Bvss3ADUBNqoBlB7Cif%2F4jjKVlmv1DYWm866ZXF3v6iGROK1%2Ft6uYQusfRwP3%2FwM%3D

**Comment by MarianaDumitriu** [comment]
![uml_secventa_casier](https://user-images.githubusercontent.com/37477360/37794296-c7485b04-2e19-11e8-8497-a099a04294fa.jpg)

**Comment by MarianaDumitriu** [comment]
Diagramele de secvenţe descriu interacţiunile dintre două sau mai multe entităţi şi ordinea în care mesajele sunt schimbate între acestea. Sun folosite în special pentru a reprezenta interacţiunile dintre obiecte. 
Diagramele de mai sus descriu scenariile de utilizare ale aplicaţiei.
Un client poate căuta un film, vizualiza informatii despre filme si deasemenea poate rezerva loc/locuri.
Administratorul este cel care are acces la baza de date si o poate modifica sau actualiza.
Prin inermediul aplicației desktop, casierul caută rezervari si confirma plata biletului.
