### ISSUE TITLE
Trebuie sa creez diagrame UML de stare.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#6]

**Comment by cristina555** [comment]
![umlstare1](https://user-images.githubusercontent.com/37477315/37792935-e3f90a18-2e15-11e8-8c32-7e0475dc7dc2.png)

**Comment by cristina555** [comment]
Diagramă de stare pentru casier cinema.

**Comment by cristina555** [comment]
![umlstare2](https://user-images.githubusercontent.com/37477315/37793119-63bebaea-2e16-11e8-8f62-b2ba161ff899.png)

**Comment by cristina555** [comment]
Diagrama de stare pentru administrator.

 Aceasta este reprezentată asemenea unui graf, şi reprezintă stările principale în care se află administratorul şi , respectiv traseele pe care le poate urma odată autentificat în sistem.

**Comment by cristina555** [comment]
![umlstare3](https://user-images.githubusercontent.com/37477315/37793264-c941d2da-2e16-11e8-965d-f297d15c0b68.png)

**Comment by cristina555** [comment]
Diagrama de stare pentru un client.

**Comment by cristina555** [comment]
Diagramele de stare au la bază două concepte importante: stările ce caracterizează valori sau seturi de valori ale obiectelor, și evenimete ce constau din stimuli externi, ce acționează asupra obiectelor și determină o tranziție de la o stare la alta. Diagramele de stare sunt grafuri, în care nodurile sunt stări și arcele direcționate sunt tranziții, având ca etichete numele evenimentelor care le-au provocat.

1.Administrator: Diagrama de stare pentru administrator reda stările principale ale aplicatiei, generate de evenimente specifice. Odata autentificat in sistem, un admin are atributia de a actualiza datele, de a gestiona filmele si programul de vizionare.
2. Casier: Diagrama de stare pentru casier specifică rolurile acestuia, evidentiate prin următoarele stări şi evenimente: Un se autentifica, încasează bani şi notează acest lucru în baza de date , de asemenea, este răspunzător de actualizarea datelor cu privire la rezervări.
3.Client: Diagrama de stare pentru un client descrie stările acestuia in timp ce navigheaza pe site-ul cinema-ului.

**Comment by Bakmy** [comment]
Cred ca pentru autentificare, ar trebui faci asa:
![image](https://user-images.githubusercontent.com/37476650/38934709-14652ab4-4325-11e8-84a7-94703551de7a.png)

Daca ti-ai bagat gresit user/parola inseamna ca nu te-ai autentificat, deci nu e necesar sa faci o bucla de genul.

**Comment by Bakmy** [comment]
Nu cred ca trebuie sa specifici "parasire site" 
![image](https://user-images.githubusercontent.com/37476650/38934920-aa0a7c72-4325-11e8-971c-31fb5b6b6176.png)

**Comment by cristina555** [comment]
Bucla ar putea exista atat timp cat incerci sa te autentifici de mai multe ori

**Comment by cristina555** [comment]
Si da..acolo trebuie sa sterg. Am pus ca alexandrescu  a zis ca vrea stare si actiune

**Comment by cristina555** [comment]
![diagrama1](https://user-images.githubusercontent.com/37477315/39100272-10048712-4690-11e8-804a-e4344bf89b0d.png)
![untitled diagram2](https://user-images.githubusercontent.com/37477315/39100273-102188c6-4690-11e8-827c-89ff25ad745b.png)
