### ISSUE TITLE
Trebuie sa creez documentatia si sa o populez cu diagramele respectiv descrierile lor.

### ISSUE THREAD

**Issue by Bakmy** [Bakmy/TiP#9]

**Comment by MarianaDumitriu** [comment]
[TIP_Documentatie.docx](https://github.com/Bakmy/TiP/files/1839406/TIP_Documentatie.docx)

**Comment by MarianaDumitriu** [comment]
[TIP_Documentatie.docx](https://github.com/Bakmy/TiP/files/1950773/TIP_Documentatie.docx)

(mai trebuie corectat diagrama de stare)

**Comment by MarianaDumitriu** [comment]
[Documentație-TI-P.docx](https://github.com/Bakmy/TiP/files/1952721/Documenta.ie-TI-P.docx)

**Comment by MarianaDumitriu** [comment]
[TIP_Documentatie.docx](https://github.com/Bakmy/TiP/files/1952726/TIP_Documentatie.docx)
